In [2]:
import tensorflow as tf
import numpy as np

In [3]:
X = np.array([[0.0,0.0],
             [0.0,1.0],
             [1.0,0.0],
             [1.0,1.0]])

In [4]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [5]:
Y=np.array([[0.0],[0.0],[0.0],[1.0]])
Y

array([[0.],
       [0.],
       [0.],
       [1.]])

In [30]:
W = tf.Variable(tf.zeros([2,1],dtype = tf.float64))

In [31]:
init = tf.global_variables_initializer()

In [32]:
camada_saida = tf.matmul(X,W)

In [33]:
def step(x):
    return tf.cast(tf.to_float(tf.math.greater_equal(x,1)),tf.float64)

In [34]:
camada_saida_ativacao = step(camada_saida)

In [37]:
erro = tf.subtract(Y,camada_saida_ativacao) 

In [49]:
delta = tf.matmul(tf.transpose(X),erro)
treinamento = tf.assign(W,tf.add(W,tf.multiply(delta,0.1)))

In [52]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(erro))
    epoca = 0
    for i in range(15):
        epoca+=1
        erro_total, _ = sess.run([erro,treinamento])
        erro_total = tf.reduce_sum(erro_total)
        print('Época:',epoca, ' Erro:',sess.run(erro_total))
    

[[0.]
 [0.]
 [0.]
 [1.]]
Época: 1  Erro: 1.0
Época: 2  Erro: 1.0
Época: 3  Erro: 1.0
Época: 4  Erro: 1.0
Época: 5  Erro: 1.0
Época: 6  Erro: 0.0
Época: 7  Erro: 0.0
Época: 8  Erro: 0.0
Época: 9  Erro: 0.0
Época: 10  Erro: 0.0
Época: 11  Erro: 0.0
Época: 12  Erro: 0.0
Época: 13  Erro: 0.0
Época: 14  Erro: 0.0
Época: 15  Erro: 0.0
