In [6]:
import tensorflow as tf

In [8]:
a = tf.constant([9,8,7], name='a')
b = tf.constant([1,2,3], name='b')

In [9]:
soma = a + b

In [10]:
type(soma)

tensorflow.python.framework.ops.Tensor

In [12]:
print(soma)

Tensor("add:0", shape=(3,), dtype=int32)


In [13]:
with tf.Session() as sess:
    print(sess.run(soma))

[10 10 10]


In [16]:
a1 = tf.constant([[1,2],[3,4]], name='a')
a2 = tf.constant([[-1,3],[4,2]], name='b')

In [19]:
multp= tf.matmul(a1,a2)

In [21]:
with tf.Session() as sess1:
    print(sess1.run(multp))

[[ 7  7]
 [13 17]]


In [26]:
b1= tf.constant([1,2,3])
b2= tf.constant([4,5,6])
dot = tf.multiply(b1,b2)
dot1 = tf.reduce_sum(dot)

In [27]:
with tf.Session() as sess2:
    print(sess2.run(dot))
    print(sess2.run(dot1))

[ 4 10 18]
32


In [28]:
p = tf.placeholder('float', None)
op = p +2

In [30]:
with tf.Session() as sess3:
    resultado = sess3.run(op,feed_dict = {p:[1,2,3]})
    print(resultado)

[3. 4. 5.]


In [31]:
p2 = tf.placeholder('float',[None,5])
op2 = p2 * 5

In [34]:
with tf.Session() as sess4:
    dados = [[1,2,3,4,5],[6,7,8,9,10]]
    result = sess4.run(op2, feed_dict = {p2:dados})
    print(result)

[[ 5. 10. 15. 20. 25.]
 [30. 35. 40. 45. 50.]]
